// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOm_121ks3cDmVY1crRMBpCEjtBXuPKPA',
    appId: '1:639236534216:web:4e96429cb87141a2079afd',
    messagingSenderId: '639236534216',
    projectId: 'sleepapnea-2f41e',
    authDomain: 'sleepapnea-2f41e.firebaseapp.com',
    storageBucket: 'sleepapnea-2f41e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANzKrEy5YSg9msv0lAhi2ijciL6EI4Elk',
    appId: '1:639236534216:android:c99a1c32c9117945079afd',
    messagingSenderId: '639236534216',
    projectId: 'sleepapnea-2f41e',
    storageBucket: 'sleepapnea-2f41e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6NBz5PfUq1ZTB1wYFEoY2f0K7TlidG2k',
    appId: '1:639236534216:ios:6024a24acf03e650079afd',
    messagingSenderId: '639236534216',
    projectId: 'sleepapnea-2f41e',
    storageBucket: 'sleepapnea-2f41e.appspot.com',
    iosBundleId: 'com.example.faceRecognition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6NBz5PfUq1ZTB1wYFEoY2f0K7TlidG2k',
    appId: '1:639236534216:ios:6024a24acf03e650079afd',
    messagingSenderId: '639236534216',
    projectId: 'sleepapnea-2f41e',
    storageBucket: 'sleepapnea-2f41e.appspot.com',
    iosBundleId: 'com.example.faceRecognition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOm_121ks3cDmVY1crRMBpCEjtBXuPKPA',
    appId: '1:639236534216:web:fda408445916a8f1079afd',
    messagingSenderId: '639236534216',
    projectId: 'sleepapnea-2f41e',
    authDomain: 'sleepapnea-2f41e.firebaseapp.com',
    storageBucket: 'sleepapnea-2f41e.appspot.com',
  );
}
